services:
  backend:
    image: auth-backend-v1
    volumes:
      - .:/simple-auth-backend-v1/
    ports:
      - "5500:4500"
    networks:
      - auth-network

networks:
  auth-network:
    driver: bridge
